//Print('++++ Show arrays ++++')
// Print(pointsperdetarr)
//Print(detrosterarr)
//Print(rosterarr)
//Print(selectarr)
// Print(unitarr)
//Print(detachmentsarr)
// Print(specialrulesarr)
//Print(adaptationarr)
// Print(traitsarr)
// Print(relicsarr)
// Print(magicarr)
//Print(rolesarr)
//Print('++++ Stop ++++')